### ISSUE TITLE
not able to drop columns

### ISSUE THREAD

**Issue by emily-elizabeth** [emily-elizabeth/Database-Designer#11]
LiveCode is using SQLite version 3.34.0 and we need 3.35.0 or greater to be able to drop a column. A workaround is to create a temp table and copy the columns we are keeping and then put it back

```
BEGIN TRANSACTION;
CREATE TEMPORARY TABLE t1_backup(a,b);
INSERT INTO t1_backup SELECT a,b FROM t1;
DROP TABLE t1;
CREATE TABLE t1(a,b);
INSERT INTO t1 SELECT a,b FROM t1_backup;
DROP TABLE t1_backup;
COMMIT;
```

**Comment by emily-elizabeth** [comment]
bug report already submitted to LiveCode
https://quality.livecode.com/show_bug.cgi?id=24051

**Comment by emily-elizabeth** [comment]
might be able to do it with `revDatabaseColumnNames` and `revDatabaseColumnTypes` and striping out the column to drop

**Comment by stam66** [comment]
Why not use revExecuteSQL and pass the code above?

**Comment by emily-elizabeth** [comment]
Because we don't know the names of the columns that are being kept, so we'd have to get the names (revDatabaseColumnNames) remove the name of the column being dropped and then rebuild the table with the new names and the column types (revDatabaseColumnTypes). Lots of work but faster than waiting for LiveCode to update the driver.

**Comment by stam66** [comment]
Actually it's trivial to get both all table names and the fields for each table with a single SQL statement:

`select * from sqlite_master where type = 'table' and name not like '%sqlite%'`
this prevents other objects such as Views from being included, as well as SQLite's internal housekeeping tables.

An example from one of my databases:
<img width="947" alt="Screenshot 2023-03-13 at 16 30 27" src="https://user-images.githubusercontent.com/5677273/224765795-435c0221-48cb-4240-984a-ec0a0e8c7946.png">

This returns a cursor with 'tbl_name' and 'sql' amongst its columns. The first is self explanatory, the second is the sql statement needed to create the table.
```
CREATE TABLE "MDM"(
	"creationTimeStamp"     DateTime DEFAULT CURRENT_TIMESTAMP,
	"createdBy"             Text,
	"modificationTimeStamp" Text,
	"modifiedBy"            Text,
	"mdmDate"               Date,
	"primaryKey"            Integer NOT NULL PRIMARY KEY AUTOINCREMENT,
	"fk_patients"           Integer,
	"completionUser"        Text,
	"completionDate"        Date,
	"clinic"                Text,
	"question"              Text,
	"history"               Text,
	"hospital"              Text,
	"location"              Text DEFAULT Outpatient,
	"presenter"             Text,
	"referrer"              Text,
	"consultant"            Text,
	"status"                Text DEFAULT Incomplete,
	"discussion"            Text,
	"sourceDocument"        Text,
	"pageCount"             Text,
	"referralDate"          Date,
	CONSTRAINT "DASHBOARD_MDM" FOREIGN KEY ( "mdmDate" ) REFERENCES "DASHBOARD"( "mdmDate" ),
	CONSTRAINT "PATIENTS_MDM" FOREIGN KEY ( "fk_patients" ) REFERENCES "PATIENTS"( "primaryKey" )
 )
```
So not only do you get the field names but also the data type and constraints for each... (and now I notice that some these need correcting in my project lol).

I was working on a database designer app and had to put it on the backburner because of other projects and actual real-life non-coding work... but the above SQL was great and analysing any SQLite db and I'm sure there are equivalents in other SQL db (although they may be pragmas).

**Comment by emily-elizabeth** [comment]
Thanks for that information.

**Comment by emily-elizabeth** [comment]
done

**Comment by emily-elizabeth** [comment]
`command DBDropColumnForSQLite databaseID, tableName, columnName
   try
      if (_DBIsOpen(databaseID)) then
         local sql
         put "select sql from sqlite_master where type = 'table' and name ='" & tableName & "'" into sql
         local createTableSQL
         put revDataFromQuery(,, databaseID, sql) into createTableSQL
         local itemNumber
         put itemOffset(columnName, createTableSQL) into itemNumber
         if (itemNumber > 0) then  // if it is 0 then deleting a column that wasn't saved to the table
            // create the temporary table
            delete item itemNumber in createTableSQL
            if (char -1 of createTableSQL <> ")") then put ")" after createTableSQL
            replace tableName with tableName & "_backup" in createTableSQL
            replace "CREATE TABLE" with "CREATE TEMPORARY TABLE" in createTableSQL
            revExecuteSQL databaseID, createTableSQL
            // insert the data from the original table into the temporary table
            local columnNames
            put revDatabaseColumnNames(databaseID, tableName) into columnNames
            put itemOffset(columnName, columnNames) into itemNumber
            delete item itemNumber in columnNames
            put "INSERT INTO " & tableName & "_backup SELECT " & columnNames & " FROM " & tableName into sql
            revExecuteSQL databaseID, sql
            // drop the original table
            put "DROP TABLE " & tableName into sql
            revExecuteSQL databaseID, sql
            // recreate the original table (dbdMainTable)
            replace "CREATE TEMPORARY TABLE" with "CREATE TABLE" in createTableSQL
            replace tableName & "_backup" with tableName in createTableSQL
            revExecuteSQL databaseID, createTableSQL
            // insert the data back into the main table
            put "INSERT INTO " & tableName & " SELECT " & columnNames & " FROM " & tableName & "_backup" into sql
            revExecuteSQL databaseID, sql
            // delete the temporary table
            put "DROP TABLE " & tableName & "_backup" into sql
            revExecuteSQL databaseID, sql
         end if
      end if
   end try
end DBDropColumnForSQLite`
