### ISSUE TITLE
[Suggestion] Show coordinates of controls for lining up easily

### ISSUE THREAD

**Issue by chrisjlocke** [emily-elizabeth/Database-Designer#20]
![image](https://user-images.githubusercontent.com/7872218/230684614-25a9c6d4-c256-48be-9302-3bf057b928a6.png)

I noticed when creating a noddy layout, that when placing label 2, it was hard to line it up with the label above.  Being able to use the cursor keys to move the control is fabulous, but it would be handy to note that label 1 was at x coordinate 100, so only have to knock label 2 across two pixels.  Or the textbox was at y coordinate 200, so the label is at the same position, etc.

When double-clicking a textbox, maybe it could jump to the same height as the last label?  (as I assume most people would work by adding a label then an input control).  Or adding a textbox at the same x coordinate as the last textbox, etc.

**Comment by emily-elizabeth** [comment]
I'll see how to implement this in the GUI. Trying to keep things simple, but I think it's a good idea.

**Comment by emily-elizabeth** [comment]
See if we can adapt this for our use
https://github.com/Ferruslogic/DevGuides/blob/main/DevGuides.livecodescript

**Comment by emily-elizabeth** [comment]
Now with guides
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/95830062/230697381-ada71050-d7b9-4474-9f37-fff6c8228b98.png">

**Comment by emily-elizabeth** [comment]
I made a new issue with the second part of the original post
